# Generated by Django 2.1.4 on 2019-01-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Новый'), (1, 'В обработке'), (2, 'Закончен'), (3, 'Ошибка')], default=0, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка для сбора')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Неизвестно'), (1, 'HTTP'), (2, 'HTTPS/SSL'), (3, 'Sock5')], default=0, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего запроса')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('latency', models.PositiveIntegerField(blank=True, null=True, verbose_name='Задержка в миллисекундах')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy.Country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
                'ordering': ('-latency',),
            },
        ),
    ]
