# Generated by Django 2.1.4 on 2018-12-28 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('PROGRESS', 'В обработке'), ('DONE', 'Закончен'), ('ERROR', 'Ошибка')], default='NEW', max_length=255, verbose_name='Статус')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка для сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('PROGRESS', 'В обработке'), ('DONE', 'Закончен'), ('ERROR', 'Ошибка')], default='NEW', max_length=255, verbose_name='Статус')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка для сбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('uid', models.CharField(blank=True, max_length=255, null=True, verbose_name='UID')),
                ('producer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopkz.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
