# Generated by Django 2.1.4 on 2018-12-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена в интернет-магазине'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена по прайсу'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена в магазинах сети'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена товара недели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(max_length=255, verbose_name='Ссылка для сбора'),
        ),
    ]
