# Generated by Django 2.1.4 on 2019-01-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkz', '0002_auto_20181229_0638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category', 'producer', 'model'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
