# Generated by Django 2.1.4 on 2018-12-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Начальная цена')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Конечная цена')),
                ('guid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код 1С')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Закупочная цена')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Розничная цена')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Специальная цена')),
                ('online_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Онлайн цена')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
