# Generated by Django 2.1.4 on 2019-01-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overclockerskz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
