# Generated by Django 2.1.4 on 2019-01-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overclockerskz', '0002_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='starting_price',
        ),
    ]
