# Generated by Django 2.1.4 on 2019-01-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overclockerskz', '0003_auto_20190102_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
