# Generated by Django 2.1.4 on 2019-01-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('overclockerskz', '0003_auto_20190102_2340'),
        ('shopkz', '0003_auto_20190102_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopkz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('overclockerskz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overclockerskz.Product', verbose_name='Продукт overclockers.kz')),
                ('shopkz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopkz.Product', verbose_name='Продукт shop.kz')),
            ],
            options={
                'verbose_name': 'Продукт shop.kz',
                'verbose_name_plural': 'Продукты shop.kz',
            },
        ),
    ]
