# Generated by Django 2.1.4 on 2019-01-03 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20190104_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkz',
            name='overclockerskz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overclockerskz.Product', verbose_name='Продукт overclockers.kz'),
        ),
        migrations.AlterField(
            model_name='shopkz',
            name='shopkz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopkz.Product', verbose_name='Продукт shop.kz'),
        ),
    ]
