# Generated by Django 2.1.4 on 2019-01-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20190104_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopkz',
            options={'ordering': ('overclockerskz', 'shopkz'), 'verbose_name': 'Продукт shop.kz', 'verbose_name_plural': 'Продукты shop.kz'},
        ),
    ]
