# Generated by Django 2.1.4 on 2019-01-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_auto_20190108_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopkz',
            options={'ordering': ('overclockerskz',), 'verbose_name': 'Продукт shop.kz', 'verbose_name_plural': 'Продукты shop.kz'},
        ),
    ]
